# Generated by Django 3.0.4 on 2020-05-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200519_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='files',
            new_name='file',
        ),
    ]
